apiVersion: operator.kyma-project.io/v1alpha1
kind: Manifest
metadata:
  labels:
    operator.kyma-project.io/channel: stable
    operator.kyma-project.io/controller-name: manifest
    operator.kyma-project.io/kyma-name: kyma-sample
  name: manifestkyma-sample
  namespace: default
spec:
  remote: false
  resource:
    kind: SampleCRD
    resource: samplecrds
    apiVersion: operator.kyma-project.io/v1alpha1
    metadata:
      name: sample-crd-from-manifest
      namespace: default
    spec:
      randomkey: samplevalue
  installs:
    - source:
        path: ""
        url: "https://github.com/kyma-project/lifecycle-manager//operator/config/default?ref=main"
        type: kustomize
      name: lifecycle-manager
    - source:
        path: "./pkg/test_samples/kustomize"
        url: ""
        type: kustomize
      name: local-chart
    - source:
        path: "./pkg/test_samples/manifest"
        url: ""
        type: kustomize
      name: local-chart
